# Generated by Django 3.2.6 on 2021-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210915_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Systems', 'Information Systems'), ('Software Engineering', 'Software Engineering'), ('Information Technology', 'Information Technology'), ('Cybersecurity', 'Cybersecurity')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')]),
        ),
    ]
