# Generated by Django 3.2.6 on 2021-12-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_choice_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_post']},
        ),
    ]
