# Generated by Django 3.2.6 on 2021-11-29 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_post', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(max_length=200)),
                ('vote', models.IntegerField(default=0)),
                ('question_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertapp.question')),
            ],
        ),
    ]
